#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Tue Jul 25 13:23:01 2023
#

import wx
import re
import os
import sys
#
sys.path.append('.')
from ParseSongs_Util import *
from ParseSongs_ProcessReq import *


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):

    # Class variables
    FilePath     = ''
    FileNameLast = ''
    #
#x  BrowserPath = '''C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'''
    BrowserPath = '''C:/Program Files/Google/Chrome/Application/chrome.exe'''
    EditorPath  = '''C:/Windows/System32/notepad.exe'''
    #
    VERSION_STRING = "Version 20230815"

    def __init__(self, *args, **kwds):
        
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((500, 575))
        self.SetTitle(u"聲調旋律分析程式")

        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"瀏覽器路徑", "")
        self.Bind(wx.EVT_MENU, self.SelectBrowserPath, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"文字編輯器路徑", "")
        self.Bind(wx.EVT_MENU, self.SelectEditorPath, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"版本", "")
        self.Bind(wx.EVT_MENU, self.ShowVersion, item)
        self.frame_menubar.Append(wxglade_tmp_menu, u"設定")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        Label_Intro1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"歡迎使用", style=wx.ALIGN_LEFT)
        Label_Intro1.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(Label_Intro1, 1, wx.BOTTOM | wx.LEFT | wx.TOP, 15)

        Label_Intro2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"聲調旋律分析程式 ♫")
        Label_Intro2.SetFont(wx.Font(30, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(Label_Intro2, 0, wx.BOTTOM | wx.LEFT, 15)

        static_line_1 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        sizer_1.Add(static_line_1, 0, wx.EXPAND, 0)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        Label_A11 = wx.StaticText(self.panel_1, wx.ID_ANY, "1")
        Label_A11.SetFont(wx.Font(28, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_2.Add(Label_A11, 1, wx.ALL, 5)

        Label_A12 = wx.StaticText(self.panel_1, wx.ID_ANY, u"請輸入以下歌曲資料")
        Label_A12.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_2.Add(Label_A12, 9, wx.TOP, 10)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND | wx.FIXED_MINSIZE, 0)

        Label_A21 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        sizer_3.Add(Label_A21, 1, 0, 0)

        SongNameLabel = wx.StaticText(self.panel_1, wx.ID_ANY, u"歌曲名稱")
        SongNameLabel.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_3.Add(SongNameLabel, 3, wx.ALL, 5)

        BeatsPerBarLabel = wx.StaticText(self.panel_1, wx.ID_ANY, u"每小節拍數")
        BeatsPerBarLabel.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_3.Add(BeatsPerBarLabel, 3, wx.ALL, 5)

        NoteFormatLabel = wx.StaticText(self.panel_1, wx.ID_ANY, u"旋律格式")
        NoteFormatLabel.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_3.Add(NoteFormatLabel, 3, wx.ALL, 5)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_4, 1, wx.EXPAND | wx.FIXED_MINSIZE, 0)

        Label_A31 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        sizer_4.Add(Label_A31, 1, 0, 0)

        self.SongNameEntry = wx.TextCtrl(self.panel_1, wx.ID_ANY, u"迷路找朋友")
        self.SongNameEntry.SetMinSize((-1, -1))
        sizer_4.Add(self.SongNameEntry, 3, wx.BOTTOM | wx.RIGHT, 15)

        self.BeatsPerBarEntry = wx.TextCtrl(self.panel_1, wx.ID_ANY, "4")
        sizer_4.Add(self.BeatsPerBarEntry, 3, wx.BOTTOM | wx.RIGHT, 15)

        self.NoteFormatEntry = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["1,2,3", "C,D,E"], style=wx.CB_DROPDOWN)
        self.NoteFormatEntry.SetSelection(0)
        sizer_4.Add(self.NoteFormatEntry, 3, wx.BOTTOM | wx.RIGHT, 15)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)

        Label_B11 = wx.StaticText(self.panel_1, wx.ID_ANY, "2")
        Label_B11.SetFont(wx.Font(28, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_5.Add(Label_B11, 1, wx.ALL, 5)

        Label_B12 = wx.StaticText(self.panel_1, wx.ID_ANY, u"請上傳你的歌曲文字檔")
        Label_B12.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_5.Add(Label_B12, 9, wx.TOP, 10)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_6, 1, wx.EXPAND, 0)

        Label_B21 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        sizer_6.Add(Label_B21, 1, 0, 0)

        self.FileButton = wx.Button(self.panel_1, wx.ID_ANY, u"按此上傳")
        self.FileButton.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_6.Add(self.FileButton, 3, wx.RIGHT | wx.TOP, 10)

        self.FileNameLabel = wx.TextCtrl(self.panel_1, wx.ID_ANY, u"(未有檔案)", style=wx.TE_READONLY)
        sizer_6.Add(self.FileNameLabel, 6, wx.LEFT | wx.RIGHT | wx.TOP, 13)

        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_9, 1, wx.EXPAND, 0)

        Label_B31 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        sizer_9.Add(Label_B31, 1, 0, 0)

        self.Label_B32 = wx.Button(self.panel_1, wx.ID_ANY, u"編輯歌曲文字檔")
        self.Label_B32.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_9.Add(self.Label_B32, 2, wx.TOP, 10)

        Label_B33 = wx.StaticText(self.panel_1, wx.ID_ANY, "")
        sizer_9.Add(Label_B33, 7, 0, 0)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_7, 1, wx.EXPAND, 0)

        Label_C11 = wx.StaticText(self.panel_1, wx.ID_ANY, "3")
        Label_C11.SetFont(wx.Font(28, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_7.Add(Label_C11, 1, wx.ALL, 5)

        Label_C12 = wx.StaticText(self.panel_1, wx.ID_ANY, u"點擊提交並執行")
        Label_C12.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_7.Add(Label_C12, 7, wx.TOP, 10)

        self.StartButton = wx.Button(self.panel_1, wx.ID_ANY, u"提交")
        self.StartButton.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.StartButton.SetForegroundColour(wx.Colour(255, 255, 255))
        self.StartButton.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_7.Add(self.StartButton, 0, wx.RIGHT | wx.TOP, 15)

        static_line_3 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        sizer_1.Add(static_line_3, 0, wx.ALL | wx.EXPAND, 0)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_8, 1, wx.EXPAND, 0)

        StatusLabel = wx.StaticText(self.panel_1, wx.ID_ANY, u"執行狀況")
        StatusLabel.SetForegroundColour(wx.Colour(0, 0, 255))
        StatusLabel.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_8.Add(StatusLabel, 2, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.LEFT | wx.TOP, 15)

        self.StatusText = wx.TextCtrl(self.panel_1, wx.ID_ANY, u"(未上傳檔案)", style=wx.TE_READONLY)
        sizer_8.Add(self.StatusText, 8, wx.ALL, 15)

        sizer_1.Add((0, 0), 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.SelectFile, self.FileButton)
        self.Bind(wx.EVT_BUTTON, self.EditFile, self.Label_B32)
        self.Bind(wx.EVT_BUTTON, self.StartClicked, self.StartButton)
        # end wxGlade

    def SelectBrowserPath(self, event):  # wxGlade: MyFrame.<event_handler>
        dlg = wx.FileDialog(
            self, message="請選擇文字編輯器路徑",
            # defaultDir=self.currentDirectory, 
            defaultFile=self.EditorPath,
            wildcard="*.exe",
            style=wx.FD_OPEN | wx.FD_MULTIPLE | wx.FD_CHANGE_DIR
            )
        if (dlg.ShowModal() == wx.ID_OK) :
            self.BrowserPath = dlg.GetPaths()[0]
            outStrB = 'BrowserPath set to ' + self.BrowserPath
            wx.MessageBox(outStrB, 'Info', wx.OK)
        # end if
        dlg.Destroy()
    # end def SelectBrowserPath()


    def SelectEditorPath(self, event):  # wxGlade: MyFrame.<event_handler>
        dlg = wx.FileDialog(
            self, message="請選擇文字編輯器路徑",
            # defaultDir=self.currentDirectory, 
            defaultFile=self.EditorPath,
            wildcard="*.exe",
            style=wx.FD_OPEN | wx.FD_MULTIPLE | wx.FD_CHANGE_DIR
            )
        if (dlg.ShowModal() == wx.ID_OK) :
            self.EditorPath = dlg.GetPaths()[0]
            outStrE = 'EditorPath set to ' + self.EditorPath
            wx.MessageBox(outStrE, 'Info', wx.OK)
        # end if
        dlg.Destroy()
    # end def SelectEditorPath()

    
    def ShowVersion(self, event):  # wxGlade: MyFrame.<event_handler>
        outStrV = self.VERSION_STRING
        wx.MessageBox(outStrV, 'Info', wx.OK)
    # end def ShowVersion()


    def SelectFile(self, event):  # wxGlade: MyFrame.<event_handler>
        dlg = wx.FileDialog(
            self, message="請選擇歌曲文字檔",
            # defaultDir=self.currentDirectory, 
            defaultFile="",
            wildcard="*.txt",
            style=wx.FD_OPEN | wx.FD_MULTIPLE | wx.FD_CHANGE_DIR
            )
        if dlg.ShowModal() == wx.ID_OK:
            paths         = dlg.GetPaths()
            self.FilePath = re.sub('\\\\', '/', paths[0])
            print('self.FilePath = ' + self.FilePath)
            fileNameLastIdx   = self.FilePath.rindex('/')
            self.FileNameLast = self.FilePath[(fileNameLastIdx+1):]
            self.FileNameLabel.SetValue(self.FileNameLast)
            self.StatusText.SetValue('(未執行)')
        # end if
        dlg.Destroy()
    # end def SelectFile()


    def EditFile(self, event):  # wxGlade: MyFrame.<event_handler>
        sysCmd = '"' + self.EditorPath + '" ' + re.sub('/', '\\\\', self.FilePath) + ''
        print('sysCmd = ' + sysCmd)
        os.system(sysCmd)
    # end def EditFile()


    def StartClicked(self, event):  # wxGlade: MyFrame.<event_handler>
        songNameVal    = self.SongNameEntry.GetValue()
        beatsPerBarVal = self.BeatsPerBarEntry.GetValue()
        noteFormatVal  = self.NoteFormatEntry.GetValue()

        if (songNameVal == '') :
            outStr0 = '請填寫歌名欄'
            wx.MessageBox(outStr0, 'Info', wx.OK)
            return
        # end if
        if (beatsPerBarVal == '') :
            outStr0 = '請填寫每小節拍數欄'
            wx.MessageBox(outStr0, 'Info', wx.OK)
            return
        # end if
        if (noteFormatVal == '') :
            outStr0 = '請填寫旋律格式欄'
            wx.MessageBox(outStr0, 'Info', wx.OK)
            return
        # end if
        if (self.FilePath == '') :
            outStr0 = '請選擇上傳歌曲'
            wx.MessageBox(outStr0, 'Info', wx.OK)
            return
        # end if

        if (noteFormatVal == '1,2,3') :
            noteFormat = 'N'
        elif (noteFormatVal == 'C,D,E') :
            noteFormat = 'A'
        else :
            showinfo(title = 'Info', message='noteFormat is not recognized')
            return
        # end if

        try :
            (code, errStr) = ProcessRequest(self.FilePath, songNameVal, int(beatsPerBarVal), noteFormat, self.BrowserPath)
        except :
            self.StatusText.SetValue('程式出現問題')
            dlg = wx.MessageDialog(None, '程式出現問題', "Info", wx.OK | wx.ICON_INFORMATION)
            dlg.ShowModal()
        else :
            self.StatusText.SetValue(errStr)
            if (code == 0) :
                outFile  = re.sub('.txt', '.html', self.FileNameLast)
                errStr  += '\n結果請查看 ' + outFile
            # end if
            dlg = wx.MessageDialog(None, errStr, "Info", wx.OK | wx.ICON_INFORMATION)
            dlg.ShowModal()
        # end if

        self.FilePath = ''
        self.FileNameLabel.SetValue('')
    # end def StartClicked()

# end of class MyFrame

class ParseSongClass(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class ParseSongClass

if __name__ == "__main__":
    ParseSong = ParseSongClass(0)
    ParseSong.MainLoop()
