#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Tue Aug 29 21:04:54 2023
#

import wx
import re
import os
import sys
#
sys.path.append('.')
from ParseSongs_Util import *
from ParseSongs_ProcessReq import *

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):

    # Class variables
    FilePath     = ''
    FileNameLast = ''
    #
#x  BrowserPath = '''C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'''
    BrowserPath = '''C:/Program Files/Google/Chrome/Application/chrome.exe'''
    EditorPath  = '''C:/Windows/System32/notepad.exe'''
    #
    VERSION_STRING = "Version 20230829"
    ABOUT_STRING = """ParseSong: Tone-Melody Correspondence Checker
Version 1.0

Copyright © 2023 
Start from the Beginning - Chinese Supporting Scheme for Non-Chinese Speaking Students in Kindergarten
Hong Kong SAR, China

--

When mentioning ParseSong: Tone-Melody Correspondence Checker in a publication, please include the following information:

URL: https://kgcsl.edu.hku.hk/software/
Project: Start from the Beginning - Chinese Supporting Scheme for Non-Chinese Speaking Students in Kindergarten

--

CO-PRINCIPAL INVESTIGATORS: 
Elizabeth K. Y. Loh
Tikky S. P. To-Chan

SOFTWARE DEVELOPMENT TEAM:
Loretta C. W. Tam (PM)
Anthony Y. W. Wong (Tech Lead)
Moses W. W. Lau (UI/UX Designer)
Fatima Hasna Hameed (QA)
Jasmine K. K. Shum (Coordinator)
Justine P. S. Woo (ECE Professional-Music)
Regina L. M. Chow (ECE Professional-Curriculum & Liaison)

SPECIAL THANKS TO:
Women's Welfare Club Western District Hong Kong Kindergarten
Yan Oi Tong Mrs Cheng Ting Kong Kindergarten
Anonymous Reviewers
Nissom Zhengliang Sun
"""

    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((560, 625))
        self.SetTitle(u"聲調旋律分析程式")
        self.SetBackgroundColour(wx.Colour(56, 63, 104))

        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"瀏覽器路徑", "")
        self.Bind(wx.EVT_MENU, self.SelectBrowserPath, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"文字編輯器路徑", "")
        self.Bind(wx.EVT_MENU, self.SelectEditorPath, item)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"關於 ParseSong", "")
        self.Bind(wx.EVT_MENU, self.ShowAbout, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"版本", "")
        self.Bind(wx.EVT_MENU, self.ShowVersion, item)
        self.frame_menubar.Append(wxglade_tmp_menu, u"設定")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_6, 0, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"\n 歡迎使用")
        label_1.SetForegroundColour(wx.Colour(255, 255, 255))
        label_1.SetFont(wx.Font(28, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_6.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM, 15)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"\n  聲調旋律分析程式 ♫")
        label_2.SetForegroundColour(wx.Colour(255, 255, 255))
        label_2.SetFont(wx.Font(28, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_LIGHT, 0, ""))
        sizer_6.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM, 15)

        static_line_1 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        static_line_1.SetBackgroundColour(wx.Colour(56, 63, 104))
        sizer_1.Add(static_line_1, 0, wx.ALL | wx.EXPAND, 15)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, u"  ① 請輸入以下歌曲資料")
        label_3.SetForegroundColour(wx.Colour(248, 159, 91))
        label_3.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_2.Add(label_3, 0, wx.TOP, 10)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 0, wx.EXPAND | wx.FIXED_MINSIZE, 0)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_7, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, u"\n   歌曲名稱")
        label_4.SetForegroundColour(wx.Colour(255, 255, 255))
        label_4.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_7.Add(label_4, 0, wx.LEFT, 5)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, u"\n  每小節拍數")
        label_5.SetForegroundColour(wx.Colour(255, 255, 255))
        label_5.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_7.Add(label_5, 0, wx.LEFT, 75)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, u"\n 旋律格式")
        label_6.SetForegroundColour(wx.Colour(255, 255, 255))
        label_6.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_7.Add(label_6, 0, wx.LEFT, 87)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_4, 0, wx.EXPAND | wx.FIXED_MINSIZE | wx.TOP, 6)

        self.SongNameEntry = wx.TextCtrl(self.panel_1, wx.ID_ANY, u"迷路找朋友")
        self.SongNameEntry.SetForegroundColour(wx.Colour(56, 63, 104))
        self.SongNameEntry.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_4.Add(self.SongNameEntry, 3, wx.LEFT | wx.RIGHT | wx.TOP, 15)

        self.BeatsPerBarEntry = wx.TextCtrl(self.panel_1, wx.ID_ANY, "4")
        self.BeatsPerBarEntry.SetForegroundColour(wx.Colour(56, 63, 104))
        self.BeatsPerBarEntry.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_4.Add(self.BeatsPerBarEntry, 3, wx.RIGHT | wx.TOP, 15)

        self.NoteFormatEntry = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["1,2,3", "C,D,E"], style=wx.CB_DROPDOWN)
        self.NoteFormatEntry.SetForegroundColour(wx.Colour(56, 63, 104))
        self.NoteFormatEntry.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.NoteFormatEntry.SetSelection(0)
        sizer_4.Add(self.NoteFormatEntry, 3, wx.RIGHT | wx.TOP, 15)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_5, 0, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, u"  ② 選擇歌曲文字檔，再按上傳檔案")
        label_7.SetForegroundColour(wx.Colour(248, 159, 91))
        label_7.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_5.Add(label_7, 0, wx.BOTTOM | wx.TOP, 30)

        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_10, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 15)

        self.FileButton = wx.Button(self.panel_1, wx.ID_ANY, u"選擇歌曲文字檔")
        self.FileButton.SetMinSize((125, 28))
        self.FileButton.SetForegroundColour(wx.Colour(56, 63, 104))
        self.FileButton.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_10.Add(self.FileButton, 3, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM, 10)

        self.FileNameLabel = wx.TextCtrl(self.panel_1, wx.ID_ANY, u"（請選擇檔案）", style=wx.TE_READONLY)
        self.FileNameLabel.SetMinSize((188, 28))
        self.FileNameLabel.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.FileNameLabel.SetForegroundColour(wx.Colour(204, 50, 50))
        self.FileNameLabel.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_10.Add(self.FileNameLabel, 4, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.LEFT, 10)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "      |    ", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_11.SetForegroundColour(wx.Colour(255, 255, 255))
        label_11.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_10.Add(label_11, 1, wx.BOTTOM, 15)

        self.EditButton = wx.Button(self.panel_1, wx.ID_ANY, u"編輯檔案")
        self.EditButton.SetMinSize((135, 28))
        self.EditButton.SetForegroundColour(wx.Colour(56, 63, 104))
        self.EditButton.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_10.Add(self.EditButton, 3, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.LEFT, 8)

        static_line_2 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        static_line_2.SetBackgroundColour(wx.Colour(56, 63, 104))
        sizer_1.Add(static_line_2, 0, wx.ALL | wx.EXPAND, 15)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, u"  ③ 點擊提交並執行")
        label_8.SetForegroundColour(wx.Colour(248, 159, 91))
        label_8.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(label_8, 0, wx.TOP, 15)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_8, 0, wx.TOP, 17)

        self.StartButton = wx.Button(self.panel_1, wx.ID_ANY, u"提交")
        self.StartButton.SetMinSize((135, 30))
        self.StartButton.SetBackgroundColour(wx.Colour(255, 253, 207))
        self.StartButton.SetForegroundColour(wx.Colour(142, 35, 107))
        self.StartButton.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_8.Add(self.StartButton, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 15)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, u"        執行狀況")
        label_9.SetMinSize((130, 20))
        label_9.SetForegroundColour(wx.Colour(255, 255, 255))
        label_9.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_8.Add(label_9, 0, wx.TOP, 3)

        self.StatusText = wx.TextCtrl(self.panel_1, wx.ID_ANY, u"（未上傳檔案）", style=wx.TE_READONLY)
        self.StatusText.SetMinSize((230, 25))
        self.StatusText.SetBackgroundColour(wx.Colour(208, 208, 208))
        self.StatusText.SetForegroundColour(wx.Colour(204, 50, 50))
        self.StatusText.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_8.Add(self.StatusText, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 7)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.SelectFile, self.FileButton)
        self.Bind(wx.EVT_BUTTON, self.EditFile, self.EditButton)
        self.Bind(wx.EVT_BUTTON, self.StartClicked, self.StartButton)
        # end wxGlade

    def SelectBrowserPath(self, event):  # wxGlade: MyFrame.<event_handler>
        dlg = wx.FileDialog(
            self, message="請選擇文字編輯器路徑",
            defaultFile=self.EditorPath,
            wildcard="*.exe",
            style=wx.FD_OPEN | wx.FD_MULTIPLE | wx.FD_CHANGE_DIR
            )
        if (dlg.ShowModal() == wx.ID_OK) :
            self.BrowserPath = dlg.GetPaths()[0]
            outStrB = 'BrowserPath set to ' + self.BrowserPath
            wx.MessageBox(outStrB, 'Info', wx.OK)
        # end if
        dlg.Destroy()
    # end def SelectBrowserPath()

    def SelectEditorPath(self, event):  # wxGlade: MyFrame.<event_handler>
        dlg = wx.FileDialog(
            self, message="請選擇文字編輯器路徑",
            defaultFile=self.EditorPath,
            wildcard="*.exe",
            style=wx.FD_OPEN | wx.FD_MULTIPLE | wx.FD_CHANGE_DIR
            )
        if (dlg.ShowModal() == wx.ID_OK) :
            self.EditorPath = dlg.GetPaths()[0]
            outStrE = 'EditorPath set to ' + self.EditorPath
            wx.MessageBox(outStrE, 'Info', wx.OK)
        # end if
        dlg.Destroy()
    # end def SelectEditorPath()

    def ShowAbout(self, event):  # wxGlade: MyFrame.<event_handler>
        wx.MessageBox(self.ABOUT_STRING, 'Info', wx.OK)
    # end def ShowAbout()

    def ShowVersion(self, event):  # wxGlade: MyFrame.<event_handler>
        outStrV = self.VERSION_STRING
        wx.MessageBox(outStrV, 'Info', wx.OK)
    # end def ShowVersion()

    def SelectFile(self, event):  # wxGlade: MyFrame.<event_handler>
        dlg = wx.FileDialog(
            self, message="請選擇歌曲文字檔",
            # defaultDir=self.currentDirectory, 
            defaultFile="",
            wildcard="*.txt",
            style=wx.FD_OPEN | wx.FD_MULTIPLE | wx.FD_CHANGE_DIR
            )
        if dlg.ShowModal() == wx.ID_OK:
            paths           = dlg.GetPaths()
            self.FilePath   = re.sub('\\\\', '/', paths[0])
            print('self.FilePath = ' + self.FilePath)
            fileNameLastIdx   = self.FilePath.rindex('/')
            self.FileNameLast = self.FilePath[(fileNameLastIdx+1):]
            self.FileNameLabel.SetValue(self.FileNameLast)
            self.StatusText.SetValue('(未執行)')
        # end if
        dlg.Destroy()
    # end def SelectFile()

    def EditFile(self, event):  # wxGlade: MyFrame.<event_handler>
        sysCmd = '"' + self.EditorPath + '" ' + re.sub('/', '\\\\', self.FilePath) + ''
        print('sysCmd = ' + sysCmd)
        os.system(sysCmd)
    # end def EditFile()
    
    def StartClicked(self, event):  # wxGlade: MyFrame.<event_handler>
        songNameVal    = self.SongNameEntry.GetValue()
        beatsPerBarVal = self.BeatsPerBarEntry.GetValue()
        noteFormatVal  = self.NoteFormatEntry.GetValue()

        if (songNameVal == '') :
            outStr0 = '請填寫歌名欄'
            wx.MessageBox(outStr0, 'Info', wx.OK)
            return
        # end if
        if (beatsPerBarVal == '') :
            outStr0 = '請填寫每小節拍數欄'
            wx.MessageBox(outStr0, 'Info', wx.OK)
            return
        # end if
        if (noteFormatVal == '') :
            outStr0 = '請填寫旋律格式欄'
            wx.MessageBox(outStr0, 'Info', wx.OK)
            return
        # end if
        if (self.FilePath == '') :
            outStr0 = '請選擇上傳歌曲'
            wx.MessageBox(outStr0, 'Info', wx.OK)
            return
        # end if

        if (noteFormatVal == '1,2,3') :
            noteFormat = 'N'
        elif (noteFormatVal == 'C,D,E') :
            noteFormat = 'A'
        else :
            showinfo(title = 'Info', message='noteFormat is not recognized')
            return
        # end if

        try :
            (code, errStr) = ProcessRequest(self.FilePath, songNameVal, int(beatsPerBarVal), noteFormat, self.BrowserPath)
        except :
            self.StatusText.SetValue('程式出現問題')
            dlg = wx.MessageDialog(None, '程式出現問題', "Info", wx.OK | wx.ICON_INFORMATION)
            dlg.ShowModal()
        else :
            self.StatusText.SetValue(errStr)
            if (code == 0) :
                outFile  = re.sub('.txt', '.html', self.FileNameLast)
                errStr  += '\n結果請查看 ' + outFile
            # end if
            dlg = wx.MessageDialog(None, errStr, "Info", wx.OK | wx.ICON_INFORMATION)
            dlg.ShowModal()
        # end if

        self.FilePath = ''
        self.FileNameLabel.SetValue('')
    # end def StartClicked()

# end of class MyFrame

class ParseSongClass(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class ParseSongClass

if __name__ == "__main__":
    ParseSong = ParseSongClass(0)
    ParseSong.MainLoop()
